# doyoudo账户每日签到赚取雪糕

# 整个工作流的名称
name: 'Doyoudo Auto Sign'

on:
  # 在推送到master分支时会自动运行一次
  push:
    branches: 
      - master
  # 可以设定定时任务执行
  schedule:
    # UTC0点30定期执行一次，跟北京时间大概相距8小时，但因为排队可能会稍微延后半小时左右
    # 即北京时间8点30以后
    - cron: '30 0 * * *'

jobs:
  # doyoudo_auto_sign为job_id，后续如果有多个job可以引用  
  doyoudo_auto_sign:
    
    # 指定运行在哪台机器上
    runs-on: ubuntu-latest

    # 该job的操作步骤
    steps:
    # 将本仓库的代码拉取一份到虚拟环境机器上
    - name: Checkout
      uses: actions/checkout@v2
    # 配置安装node环境
    - name: 'Set up nodejs'
      uses: actions/setup-node@v1.4.4
      with:
        node-version: '12.x'
    # 安装PM2来后台运行站点
    - name: 'install pm2'
      run: npm install pm2 -g
    # 启动运行PM2服务
    - name: 'run node server, using PM2'
      run: pm2 start ./js_encrypt_server/aes-server.js
    # 配置安装python环境
    - name: 'Set up Python'
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
    # 配置安装依赖包
    - name: 'Install requirements'
      run: pip install -r requirements.txt
    # 运行python脚本文件，其中的参数取secrets中配置的加密参数，账户名和密码
    - name: 'Working'
      run: python doyoudo_auto_sign.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }}
    # 停止PM2服务
    - name: 'Stop PM2 service'
      run: pm2 stop all
    # 发送日志邮件
    - name: send log mail
      uses: dawidd6/action-send-mail@v2.2.2
      with:
        server_address: smtp.qq.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: doyoudo签到情况
        body: file://log.log
        to: ${{ secrets.MAIL_TO }}
        from: GitHub Actions
        content_type: text/plain