# doyoudo 账户每日签到赚取雪糕

# 整个工作流的名称
name: 'Doyoudo Auto Sign'

on:
  # 在推送到 master 分支时会自动运行一次
  push:
    branches: 
      - master
  # 可以设定定时任务执行
  schedule:
    # UTC 0 点 30 定期执行一次，跟北京时间大概相距 8 小时，但因为排队可能会稍微延后半小时左右
    # 即北京时间 8 点 30 以后
    - cron: '30 0 * * *'

jobs:
  # doyoudo_auto_sign 为 job_id，后续如果有多个 job 可以引用  
  doyoudo_auto_sign:
    
    # 指定运行在哪台机器上
    runs-on: ubuntu-latest

    # 该 job 的操作步骤
    steps:
    # 将本仓库的代码拉取一份到虚拟环境机器上
    - name: Checkout
      uses: actions/checkout@v2
    # 配置安装 node 环境
    - name: 'Set up nodejs'
      uses: actions/setup-node@v1.4.4
      with:
        node-version: '12.x'
    # 安装 PM2 来后台运行站点
    - name: 'install pm2'
      run: npm install pm2 -g
    # 启动运行 PM2 服务
    - name: 'run node server, using PM2'
      run: pm2 start ./js_encrypt_server/aes-server.js
    # 配置安装 python 环境
    - name: 'Set up Python'
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
    # 配置安装依赖包
    - name: 'Install requirements'
      run: pip install -r requirements.txt
    # 运行 python 脚本文件，其中的参数取 secrets 中配置的加密参数，账户名和密码
    - name: 'Working'
      run: python doyoudo_auto_sign.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }}
    # 停止 PM2 服务
    - name: 'Stop PM2 service'
      run: pm2 stop all
    # 发送日志邮件
    - name: send log mail
      uses: dawidd6/action-send-mail@v2.2.2
      with:
        # qq 邮箱默认 server 写 stmp.qq.com，如果是腾讯企业邮，则写 smtp.exmail.qq.com
        server_address: ${{ secrets.MAIL_SMTP_SERVER }}
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: doyoudo 签到情况
        body: file://log.log
        to: ${{ secrets.MAIL_TO }}
        from: GitHub Actions
        content_type: text/plain